US_STATES = (
    ('AL', 'Alabama'),
    ('AK', 'Alaska'),
    ('AZ', 'Arizona'),
    ('AR', 'Arkansas'),
    ('CA', 'California'),
    ('CO', 'Colorado'),
    ('CT', 'Connecticut'),
    ('DE', 'Delaware'),
    ('FL', 'Florida'),
    ('GA', 'Georgia'),
    ('HI', 'Hawaii'),
    ('ID', 'Idaho'),
    ('IL', 'Illinois'),
    ('IN', 'Indiana'),
    ('IA', 'Iowa'),
    ('KS', 'Kansas'),
    ('KY', 'Kentucky'),
    ('LA', 'Louisiana'),
    ('ME', 'Maine'),
    ('MD', 'Maryland'),
    ('MA', 'Massachusetts'),
    ('MI', 'Michigan'),
    ('MN', 'Minnesota'),
    ('MS', 'Mississippi'),
    ('MO', 'Missouri'),
    ('MT', 'Montana'),
    ('NE', 'Nebraska'),
    ('NV', 'Nevada'),
    ('NH', 'New Hampshire'),
    ('NJ', 'New Jersey'),
    ('NM', 'New Mexico'),
    ('NY', 'New York'),
    ('NC', 'North Carolina'),
    ('ND', 'North Dakota'),
    ('OH', 'Ohio'),
    ('OK', 'Oklahoma'),
    ('OR', 'Oregon'),
    ('PA', 'Pennsylvania'),
    ('RI', 'Rhode Island'),
    ('SC', 'South Carolina'),
    ('SD', 'South Dakota'),
    ('TN', 'Tennessee'),
    ('TX', 'Texas'),
    ('UT', 'Utah'),
    ('VT', 'Vermont'),
    ('VA', 'Virginia'),
    ('WA', 'Washington'),
    ('WV', 'West Virginia'),
    ('WI', 'Wisconsin'),
    ('WY', 'Wyoming'),
)

RESERVATION_STATUSES = (
    ('A', 'Approved'),
    ('AC', 'Active'),
    ('C', 'Cancelled'),
    ('CL', 'Closed'),
    ('O', 'Overdue'),
    ('P', 'Pending'),
    ('R', 'Rejected'),
    ('RA', 'Return Acknowledged'),
    ('RC', 'Recalled'),
    ('RI', 'Return Initiated'),
)

TOOL_STATUS = (
    ('A', 'Available'),
    ('D', 'Deactivated'),
)

TOOL_LOCATION = (
    ('H', 'Home'),
    ('S', 'Shed')
)

TOOL_CATEGORY = (
    ('BL', 'Blades'),
    ('BR', 'Braces'),
    ('BS', 'Brushes'),
    ('CA', 'Calipers'),
    ('CH', 'Chisel'),
    ('CL', 'Clamps'),
    ('CP', 'Clips'),
    ('CM', 'Compressors'),
    ('CU', 'Cutters'),
    ('DI', 'Dispenser'),
    ('DR', 'Drills'),
    ('GA', 'Gauges'),
    ('GR', 'Grinder'),
    ('HA', 'Hammer'),
    ('HX', 'Hand Axe'),
    ('HT', 'Hedge Trimmers'),
    ('LA', 'Ladders'),
    ('LM', 'Lawn Mowers'),
    ('MT', 'Measuring Tape/Ruler'),
    ('MI', 'Micrometer'),
    ('NG', 'Nail Gun'),
    ('PL', 'Pliers'),
    ('SA', 'Sanders'),
    ('SW', 'Saws'),
    ('SC', 'Scissors'),
    ('SD', 'Screwdrivers'),
    ('SH', 'Shovel'),
    ('TB', 'Toolbox'),
    ('TR', 'Trowel'),
    ('WE', 'Welding/ Soldering'),
    ('WR', 'Wrenches'),
    ('OT', 'Other'),
)